### ISSUE TITLE
Is this available for Ubuntu?

### ISSUE THREAD

**Issue by hemangjoshi37a** [microsoft/WindowsAgentArena#15]
Is this available for Ubuntu?

**Comment by francedot** [comment]
We do not support running of the Navi agent on Ubuntu. We support instead running of the Windows KVM on the Docker from a Ubuntu host.

**Comment by hemangjoshi37a** [comment]
ok then . if possible please support Ubuntu because here in our company we have 1000 computers running Ubuntu 22.04
