### ISSUE TITLE
Running the base benchmark tasks on local: How to run specific tasks/category

### ISSUE THREAD

**Issue by asc0216** [microsoft/WindowsAgentArena#23]
I followed the readme to run the tasks using 
```
./run-local.sh --start-client true
```
I see no change in the terminal atleast for ~1 hour: 
![image](https://github.com/user-attachments/assets/a89c790c-5dfe-4907-b299-e6e73e5f2f37)

Questions: 
- what is the expected output when running the benchmark?
- how can I run a subset of the tasks?

**Comment by francedot** [comment]
Could you share the content of the `ps_script_log.txt`? You can find the log file in the Setup folder on the desktop of the running VM. You can access the VM at `localhost:8006` if using a browser or `localhost:3390` if using RDP. More information on how to troubleshoot the preparation step can be found [here](https://github.com/microsoft/WindowsAgentArena/blob/main/docs/Development-Tips.md).

**Comment by dznyu** [comment]
The expected output when run locally typically comes out as a reported success score logged or printed to terminal/console--one after each task (1 if successful, 0 if not or a value between 0 and 1 if the task relies on some similarity measure) and one after each group of tasks or after all tasks are done for an overall success rate. The list of scores/rewards are stored in a list that's appended to as the benchmark loops through tasks so it should be straightforward to save them out if you need it for your own purposes.

To run a subset of the tasks, all you have to do is create a new json file similar to those that exist under 
`/win-arena-container/client/evaluation_examples_windows`. The new json should mimic the other jsons that are there in that the keys should be the category/application of the tasks and the values should be a list of the task IDs for each one of the keys. For instance, you could make a copy of `test_all.json` and edit that down to the subset of tasks you want by keeping the programs and IDs corresponding to your desired tasks.

**Comment by asc0216** [comment]
the ps_script_log.txt looks like the below, I see failures with installing LibreOffice and pip: 
![image](https://github.com/user-attachments/assets/dc0e58db-a39c-47b5-a150-83abcd92f791)
![image](https://github.com/user-attachments/assets/9de23fe3-5558-4a85-8c59-1b6683faa69c)
![image](https://github.com/user-attachments/assets/34a5e9bd-6200-47ef-97db-f8932bb1b4f0)
![image](https://github.com/user-attachments/assets/38b63c56-73d9-4c5d-ade5-e9001ad70f82)

**Comment by francedot** [comment]
This should have been addressed as per #24:

1. Pull the latest changes from the main branch.
2. Run `docker pull windowsarena/winarena:latest`.
3. Remove any existing content in `src/win-arena-container/vm/storage`.
4. Execute again `./run-local --prepare-image true`.

**Comment by francedot** [comment]
Closing for now. Let me know if you're still experiencing any issues at the preparation step.

**Comment by asc0216** [comment]
Are there any additional files that I need to remove? I pulled the latest but I run into the error:
`docker: Error response from daemon: error while creating mount source path '/run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/1dc62cb239012173abe53dfd7d48092fb92164fc277668f25c5839dcce5d8fe5': mkdir /run/desktop/mnt/host/wsl/docker-desktop-bind-mounts/Ubuntu/1dc62cb239012173abe53dfd7d48092fb92164fc277668f25c5839dcce5d8fe5: file exists.`
