### ISSUE TITLE
Incorrect gpt version select when single test

### ISSUE THREAD

**Issue by WhiteFlamesCN** [microsoft/WindowsAgentArena#25]
hi there, I am trying to change the version of gpt using "--model" to specify. However , when input "gpt-4o", it finally use gpt4v 1106 preview instead ,which returns invalid for openai api. When I hardcode this in gpt4v_oai.py , everything gets fine.So I wonder if some settings replaced this in single deploy.

BTW,when this happened, the process is stocked in "Thinking" and keep on waiting , which is really confusing when I first encountered this problem.

**Comment by francedot** [comment]
The `--model` argument propagation issue should have been resolved with PR #26. Let us know if you're still experiencing any issues.
