### ISSUE TITLE
Dockerfile for "windows-local"

### ISSUE THREAD

**Issue by matbee-eth** [microsoft/WindowsAgentArena#38]
Which Dockerfile is used to build "agentarena/windows-local"?

**Comment by francedot** [comment]
https://github.com/francedot/windows-local

It was forked and simplified from [dockur/windows](https://github.com/dockur/windows)

**Comment by matbee-eth** [comment]
I ended up just using the dockur/windows image and adding the missing run scripts, etc.
Thanks!
