### ISSUE TITLE
Failed to connect to QMP

### ISSUE THREAD

**Issue by 18277390221** [microsoft/WindowsAgentArena#42]
I have such a problem when running the run-local.sh file, is there any solution, thank you very much!

![Image](https://github.com/user-attachments/assets/5520a41b-7bcb-4519-94be-622ca7352b05)

![Image](https://github.com/user-attachments/assets/fa6f7065-0364-47a7-98c3-b2d83703773b)

**Comment by ddupont808** [comment]
Hi, can you try building the base image to see if that fixes it?

The command is `./build-container-image.sh --build-base-image true`
Once that's done you should be able to do `./run-local.sh`

**Comment by 18277390221** [comment]
> Hi, can you try building the base image to see if that fixes it?
> 
> The command is `./build-container-image.sh --build-base-image true` Once that's done you should be able to do `./run-local.sh`

I took care of it. Thank you so much！！
